document.documentElement.classList.toggle('windows-desktop',/Windows/i.test(navigator.userAgentData?.platform||navigator.platform||navigator.userAgent));

const board=document.querySelector('#artboard'),viewport=document.querySelector('#viewport');
function fit(){if(!viewport.clientWidth)return;const scale=viewport.clientWidth/1728;board.style.transform=`scale(${scale})`;viewport.style.height=`${5538*scale}px`}fit();addEventListener('resize',fit);
const node=id=>document.querySelector(`[data-node-id="${id}"]`);
function link(id,href,label,kind='interactive'){const old=node(id);if(!old)return;const a=document.createElement('a');old.querySelectorAll('a').forEach(child=>{const div=document.createElement('div');for(const attr of child.attributes)if(attr.name!=='href'&&attr.name!=='target')div.setAttribute(attr.name,attr.value);while(child.firstChild)div.append(child.firstChild);child.replaceWith(div)});for(const attr of old.attributes)a.setAttribute(attr.name,attr.value);a.href=href;a.setAttribute('aria-label',label);a.classList.add(kind);while(old.firstChild)a.append(old.firstChild);old.replaceWith(a);return a}
[['212:113','work'],['212:203','about'],['212:283','contact']].forEach(([n,id])=>{if(node(n))node(n).id=id});
[['212:92','#work','Selected work'],['212:94','#about','About Edanur'],['212:96','#contact','Contact'],['212:108','#work','View selected work'],['212:98','home-assets/Edanur-Gunduz-CV-English.pdf?v=20261009-cv-final','Download CV'],['212:293','mailto:edgunduuz001@gmail.com','Say hello'],['212:299','https://www.linkedin.com/in/eda-g%C3%BCnd%C3%BCz-01/','LinkedIn'],['212:302','https://www.behance.net/edagndz1','Behance']].forEach(x=>link(...x));
[['225:914','afterimage-scroll-story.html','Afterimage case study'],['225:915','shoco-scroll-story.html','ShoCo case study'],['243:250','steal-and-seal-scroll-story.html','Steal & Seal case study'],['243:263','multiwars-scroll-story.html','Card UI Design case study'],['243:290','foody-scroll-story.html','Foody case study']].forEach(x=>link(...x,'project-link'));
document.querySelectorAll('a[href^="#"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();const target=document.querySelector(a.hash);if(!target)return;const y=target.getBoundingClientRect().top+scrollY;window.scrollTo({top:y,behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});history.replaceState(null,'',a.hash)}));
['212:111','212:112'].forEach((id,i)=>{node(id)?.classList.add('hero-phone');if(i)node(id)?.classList.add('second')});
document.documentElement.classList.add('motion-ready');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});['212:117','212:122','212:186','212:193','19:460','212:206','212:210','212:221','212:225','212:233','212:243','212:251','212:261','212:264','212:267','212:274','212:289'].forEach(id=>{const n=node(id);if(n){n.classList.add('reveal');observer.observe(n)}});

// Compact layouts reuse the exact Figma artwork, copy and destinations.
const readable=n=>n?(n.children.length?[...n.children].map(readable).join(' '):n.textContent).replace(/\s+/g,' ').trim():'';const textOf=id=>readable(node(id));
const mobile=document.createElement('main');mobile.className='mobile-home';mobile.id='mobile-top';
const element=(tag,cls,text)=>{const n=document.createElement(tag);n.className=cls||'';if(text)n.textContent=text;return n};
function anchor(text,href,cls){const a=element('a',cls,text);a.href=href;return a}
const nav=element('nav','mobile-nav');nav.append(anchor('Edanur Gündüz','#mobile-top'));const navlinks=element('div','mobile-nav-links');[['Work','#mobile-work'],['About','#mobile-about'],['CV','home-assets/Edanur-Gunduz-CV-English.pdf?v=20261009-cv-final']].forEach(x=>navlinks.append(anchor(...x)));nav.append(navlinks);mobile.append(nav);
const hero=element('section','mobile-hero');hero.append(element('p','tag',textOf('212:101')));const h1=element('h1');h1.append(element('span','',textOf('212:105')),document.createElement('br'),element('span','',textOf('212:106')));hero.append(h1,element('p','intro',textOf('212:107')),anchor('View selected work ↓','#mobile-work','mobile-cta'));mobile.append(hero);
function mobileProjects(title,id,cards){const section=element('section','mobile-section');section.id=id;section.append(element('h2','',title));cards.forEach(([artId,name,meta,url,wide])=>{const a=anchor('',url,'mobile-card'),art=element('div','mobile-card-art'),stage=element('div','mobile-card-stage'+(wide?' wide':''));const cardWidth=typeof wide==='number'?wide:587;stage.style.width=cardWidth+'px';stage.dataset.cardWidth=String(cardWidth);art.style.aspectRatio=cardWidth+'/383';const source=node(artId);if(!source)return;const original=source.cloneNode(true);[original,...original.querySelectorAll('[data-node-id]')].forEach(n=>n.removeAttribute('data-node-id'));original.removeAttribute('href');original.querySelectorAll('[id]').forEach(n=>n.removeAttribute('id'));original.classList.remove('hero-phone','fade-in','reveal','project-link');original.style.translate='0 0';stage.append(original);art.append(stage);a.append(art,element('h3','',name),element('small','',meta));section.append(a)});mobile.append(section)}
mobileProjects('Selected Work','mobile-work',[['243:293',textOf('243:296'),'Mobile App · View Project ↗','foody-scroll-story.html',354],['212:194',textOf('212:197'),'Mobile App · View Project ↗','afterimage-scroll-story.html',354],['212:122',textOf('212:187'),'Mobile App · View Project ↗','shoco-scroll-story.html',587],['243:253',textOf('243:257'),'Game HUD · View Project ↗','steal-and-seal-scroll-story.html',587],['243:266',textOf('243:268'),'Card Interface Design · View Project ↗','multiwars-scroll-story.html',354]]);
const about=element('section','mobile-section mobile-about');about.id='mobile-about';about.append(element('h2','','About Me'));const photo=element('img');photo.src='assets/home/imgFrame15.webp';photo.alt='Edanur Gündüz';about.append(photo);const aboutText=node('212:214');if(aboutText)aboutText.textContent.split(/\n\s*\n/).filter(t=>t.trim()).forEach(t=>about.append(element('p','',t.trim())));about.append(element('p','skills',textOf('212:215')));mobile.append(about);
const exp=element('section','mobile-section mobile-experience');exp.append(element('h2','','Experience & Education'));['212:225','212:233','212:243','212:251'].forEach(id=>{const source=node(id)?.parentElement;if(source){const row=element('div','row');source.querySelectorAll('p').forEach(p=>row.append(element('small','',p.textContent)));exp.append(row)}});mobile.append(exp);

const contact=element('section','mobile-contact');const contactLine=element('p');const contactSource=node('212:292');if(contactSource)contactLine.innerHTML=contactSource.innerHTML;contact.append(element('h2','',textOf('212:291')),contactLine,anchor('Say hello ↗','mailto:edgunduuz001@gmail.com','mobile-cta'));const social=element('div','mobile-social');social.append(anchor('LinkedIn ↗','https://www.linkedin.com/in/eda-g%C3%BCnd%C3%BCz-01/'),anchor('Behance ↗','https://www.behance.net/edagndz1'));contact.append(social);mobile.append(contact);const foot=element('footer','mobile-footer');const signature=element('div');signature.append(element('p','',textOf('220:878')),element('p','signature',textOf('220:879')));foot.append(signature,anchor(textOf('220:880'),'#mobile-top'));mobile.append(foot);document.body.append(mobile);

// Fit the highlight bars to the rendered font, with a small overhang.
function sizeHighlights(){const first=node('212:105'),second=node('212:106');const purple=node('212:87'),inner=purple?.firstElementChild?.firstElementChild;const lime=node('212:88');if(!first||!purple)return;const measure=p=>{const range=document.createRange();range.selectNodeContents(p);if(p.firstChild?.nodeType===Node.TEXT_NODE)range.setEnd(p.firstChild,p.firstChild.textContent.trimEnd().length);const scale=viewport.clientWidth/1728;return range.getBoundingClientRect().width/(scale||1)};const w1=measure(first)+24,w2=measure(second)+24;purple.style.width=(w1+4)+'px';if(inner)inner.style.width=w1+'px';if(lime)lime.style.width=w2+'px';}
document.fonts.ready.then(sizeHighlights);addEventListener('resize',sizeHighlights);

const backToTop=node('220:880');if(backToTop){backToTop.tabIndex=0;backToTop.setAttribute('role','button');const back=()=>window.scrollTo({top:0,behavior:reduced.matches?'instant':'smooth'});backToTop.addEventListener('click',back);backToTop.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();back()}})}

function fitCards(){document.querySelectorAll('.mobile-card-stage').forEach(stage=>{const width=stage.parentElement.clientWidth;if(width>0)stage.style.setProperty('--card-scale',width/Number(stage.dataset.cardWidth))})}fitCards();
let layoutFrame;function updateLayout(){cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(()=>{fit();fitCards();sizeHighlights()})}
addEventListener('resize',updateLayout);matchMedia('(max-width:760px)').addEventListener('change',updateLayout);
const layoutObserver=new ResizeObserver(updateLayout);layoutObserver.observe(viewport);document.querySelectorAll('.mobile-card-art').forEach(n=>layoutObserver.observe(n));
document.fonts.ready.then(updateLayout);
